# Site settings
title: Enkimail
email: info@enkimail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown

# Team names, titles and social links
people:
- name: Albert Oliva
  pic: 1
  position: Founder · Lead Backend Developer
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/albertoliva/
    - title: github
      url: https://github.com/aiw3ndil
    - title: twitter
      url: https://twitter.com/aiw3ndil